# Generated by Django 4.0.4 on 2022-09-27 16:11

import common.encrypted_fields
from django.db import migrations


def forwards(apps, schema_editor):
    SocialToken = apps.get_model('socialaccount', 'SocialToken')
    for obj in SocialToken.objects.all():
        obj.token_encrypted = obj.token
        obj.token_secret_encrypted = obj.token_secret
        obj.save(update_fields=['token_encrypted', 'token_secret_encrypted'])


def backwards(apps, schema_editor):
    SocialToken = apps.get_model('socialaccount', 'SocialToken')
    for obj in SocialToken.objects.all():
        obj.token = obj.token_encrypted
        obj.token_secret = obj.token_secret_encrypted
        obj.save(update_fields=['token', 'token_secret'])


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialtoken',
            name='token_encrypted',
            field=common.encrypted_fields.EncryptedTextField(blank=True),
        ),
        migrations.AddField(
            model_name='socialtoken',
            name='token_secret_encrypted',
            field=common.encrypted_fields.EncryptedTextField(blank=True),
        ),
        migrations.RunPython(forwards, reverse_code=backwards),
        migrations.RemoveField(
            model_name='socialtoken',
            name='token',
        ),
        migrations.RemoveField(
            model_name='socialtoken',
            name='token_secret',
        ),
        migrations.RenameField(
            model_name='socialtoken',
            old_name='token_encrypted',
            new_name='token',
        ),
        migrations.RenameField(
            model_name='socialtoken',
            old_name='token_secret_encrypted',
            new_name='token_secret',
        ),
    ]
